logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048
  port: 1988

spring:
  jackson:
    serialization:
     write-dates-as-timestamps: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

debug: true

initializr:
  dependencies:
    - name: Ui Librairies
      content:
        - name: gwt-polymer-elements
          id: gwt-polymer
          artifactId: vaadin-gwt-polymer-elements
          scope: provided
          groupId: com.vaadin.polymer
          description: Ready to use Polymer elements GWT projects
          version: 1.7.0.0
          starter: false
        - name: gwt-material
          id: gwtmaterial
          artifactId: vaadin-gwt-polymer-elements
          scope: provided
          groupId: com.github.gwtmaterialdesign
          description: gwt-material
          version: 1.6
          starter: false
        - name: gwtbootstrap3
          id: gwtbootstrap
          description: a Material Design wrapper for GWT
          version: 0.9.3
          artifactId: vaadin-gwt-polymer-elements
          scope: provided
          groupId: com.github.gwtmaterialdesign
          starter: false
    - name: Rest/HTTP
      content:
        - name: Web
          id: web
          description: Full-stack web development with Tomcat and Spring MVC
          weight: 100
          facets:
            - web
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: gwt-app
      id: gwt-app
      default: true
    - name: gwt-lib
      id: gwt-lib
      default: false
  javaVersions:
    - id: 1.8
      default: true
    - id: 1.7
      default: false
  gwtVersions:
    - name : 2.8.0
      id: 2.8.0
      default: true
    - name: 2.7.0
      id: 2.7.0
      default: false

