language: java

jdk:
  - oraclejdk8

before_deploy: cd gwt-project-generator-service

deploy:
  edge: true
  provider: cloudfoundry
  username: $CI_PWS_USERNAME
  password: $CI_PWS_PASSWORD
  api: https://api.run.pivotal.io
  organization: $CI_PWS_ORG
  space: gwt-project-generator
